// 
// Copyright (c) 2023-2025 REghZy
// 
// This file is part of FramePFX.
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with FramePFX. If not, see <https://www.gnu.org/licenses/>.
// 

namespace PFXToolKitUI.Avalonia.Themes;

public static class BaseDarkThemeControlColourMappings {
    public static (string, string?)[] Inheritance => [
        // "ThemeKey",                                       "InheritFrom"
        ("PanelBorderBrush",                                 "ABrush.Tone1.Border.Static"),
        ("PanelBackground0",                                 "ABrush.Tone0.Background.Static"),
        ("PanelBackground1",                                 "ABrush.Tone1.Background.Static"),
        ("PanelBackground2",                                 "ABrush.Tone2.Background.Static"),
        ("PanelBackground3",                                 "ABrush.Tone3.Background.Static"),
        ("PanelBackground4",                                 "ABrush.Tone4.Background.Static"),
        ("Button.Static.Background",                         "ABrush.Tone5.Background.Static"),
        ("Button.Static.Border",                             "ABrush.Tone5.Border.Static"),
        ("Button.MouseOver.Background",                      "ABrush.Tone5.Background.MouseOver"),
        ("Button.MouseOver.Border",                          "ABrush.Tone5.Border.MouseOver"),
        ("Button.Pressed.Background",                        "ABrush.Tone5.Background.MouseDown"),
        ("Button.Pressed.Border",                            "ABrush.Tone5.Border.MouseDown"),
        ("Button.Disabled.Background",                       "ABrush.Tone5.Background.Disabled"),
        ("Button.Disabled.Border",                           "ABrush.Tone5.Border.Disabled"),
        ("Button.Static.Foreground",                         "ABrush.Foreground.Static"),
        ("Button.Disabled.Foreground",                       "ABrush.Foreground.Disabled"),
        ("Button.Defaulted.Background",                      "ABrush.ColourfulGlyph.Static"),
        ("Button.Defaulted.Border",                          "ABrush.ColourfulGlyph.Disabled"),
        ("ButtonSpinner.Error.Border",                       null),
        ("ToggleButton.IsChecked.Background",                "ABrush.AccentTone2.Background.Static"),
        ("ToggleButton.IsChecked.Border",                    "ABrush.AccentTone2.Border.Static"),
        ("ToggleButton.Pressed.IsChecked.Background",        "ABrush.Tone6.Border.Selected"),
        ("ToggleButton.Pressed.IsChecked.Border",            "ABrush.Tone6.Border.Selected"),
        ("ToggleButton.MouseOver.IsChecked.Background",      "ABrush.AccentTone1.Background.Static"),
        ("ToggleButton.MouseOver.IsChecked.Border",          "ABrush.AccentTone1.Border.Static"),
        ("ComboBox.Static.Background",                       "ABrush.Tone4.Background.Static"),
        ("ComboBox.Static.Border",                           "ABrush.Tone6.Border.Static"),
        ("ComboBox.Static.Foreground",                       "ABrush.Foreground.Static"),
        ("ComboBox.Static.Editable.Background",              "ABrush.Tone4.Background.Static"),
        ("ComboBox.Static.Editable.Border",                  "ABrush.Tone4.Border.Static"),
        ("ComboBox.Static.Editable.Button.Background",       null),
        ("ComboBox.Static.Editable.Button.Border",           null),
        ("ComboBox.Button.Static.Background",                "ABrush.Tone5.Background.Static"),
        ("ComboBox.Button.Static.Border",                    "ABrush.Tone6.Border.Static"),
        ("ComboBox.MouseOver.Glyph",                         "ABrush.Glyph.MouseOver"),
        ("ComboBox.MouseOver.Background",                    "ABrush.Tone4.Background.MouseOver"),
        ("ComboBox.MouseOver.Border",                        "ABrush.Tone4.Border.MouseOver"),
        ("ComboBox.MouseOver.Editable.Background",           "ABrush.Tone4.Background.MouseOver"),
        ("ComboBox.MouseOver.Editable.Border",               "ABrush.Tone4.Border.MouseOver"),
        ("ComboBox.MouseOver.Editable.Button.Background",    null),
        ("ComboBox.MouseOver.Editable.Button.Border",        null),
        ("ComboBox.Pressed.Glyph",                           "ABrush.Glyph.MouseDown"),
        ("ComboBox.Pressed.Background",                      "ABrush.Tone4.Background.MouseDown"),
        ("ComboBox.Pressed.Border",                          "ABrush.Tone4.Border.MouseDown"),
        ("ComboBox.Pressed.Editable.Background",             "ABrush.Tone4.Background.MouseDown"),
        ("ComboBox.Pressed.Editable.Border",                 "ABrush.Tone4.Border.MouseDown"),
        ("ComboBox.Pressed.Editable.Button.Background",      null),
        ("ComboBox.Pressed.Editable.Button.Border",          null),
        ("ComboBox.Disabled.Glyph",                          "ABrush.Glyph.Disabled"),
        ("ComboBox.Disabled.Background",                     "ABrush.Tone4.Background.Disabled"),
        ("ComboBox.Disabled.Border",                         "ABrush.Tone4.Border.Disabled"),
        ("ComboBox.Disabled.Editable.Background",            "ABrush.Tone4.Background.Disabled"),
        ("ComboBox.Disabled.Editable.Border",                "ABrush.Tone4.Border.Disabled"),
        ("ComboBox.Disabled.Editable.Button.Background",     null),
        ("ComboBox.Disabled.Editable.Button.Border",         null),
        ("ComboBox.Static.Glyph",                            "ABrush.Glyph.Static"),
        ("ComboBoxItem.ItemView.Hover.Background",           "ABrush.Tone5.Background.MouseOver"),
        ("ComboBoxItem.ItemView.Hover.Border",               "ABrush.Tone5.Border.MouseOver"),
        ("ComboBoxItem.ItemView.Selected.Background",        "ABrush.Tone5.Background.Selected"),
        ("ComboBoxItem.ItemView.Selected.Border",            "ABrush.Tone5.Border.Selected"),
        ("ComboBoxItem.ItemView.SelectedHover.Background",   "ABrush.Tone5.Background.Selected"),
        ("ComboBoxItem.ItemView.SelectedHover.Border",       "ABrush.Tone5.Border.Selected"),
        ("ComboBoxItem.ItemView.SelectedNoFocus.Background", "ABrush.Tone5.Background.Selected.Inactive"),
        ("ComboBoxItem.ItemView.SelectedNoFocus.Border",     "ABrush.Tone5.Border.Selected.Inactive"),
        ("ComboBoxItem.ItemView.Focus.Border",               "ABrush.Tone5.Border.Static"),
        ("ComboBoxItem.ItemView.HoverFocus.Background",      "ABrush.Tone5.Background.MouseOver"),
        ("ComboBoxItem.ItemView.HoverFocus.Border",          "ABrush.Tone5.Border.MouseOver"),
        ("TextBox.Static.Background",                        "ABrush.Tone4.Background.Static"),
        ("TextBox.Static.Border",                            "ABrush.Tone5.Border.Static"),
        ("TextBox.MouseOver.Border",                         "ABrush.Tone5.Border.MouseOver"),
        ("TextBox.Focus.Border",                             "ABrush.ColourfulGlyph.Static"),
        ("TextBox.Selection.Inactive",                       "ABrush.ColourfulGlyph.Selected.Inactive"),
        ("TextBox.Selection",                                "ABrush.ColourfulGlyph.Selected"),
        ("TextBox.Error.Border",                             null),
        ("ListBox.Static.Background",                        "ABrush.Tone4.Background.Static"),
        ("ListBox.Static.Border",                            "ABrush.Tone4.Border.Static"),
        ("ListBox.Disabled.Background",                      "ABrush.Tone4.Background.Disabled"),
        ("ListBox.Disabled.Border",                          "ABrush.Tone4.Border.Disabled"),
        ("ListBoxItem.MouseOver.Background",                 "ABrush.Tone5.Background.MouseOver"),
        ("ListBoxItem.MouseOver.Border",                     "ABrush.Tone5.Border.MouseOver"),
        ("ListBoxItem.SelectedInactive.Background",          "ABrush.Tone5.Background.Selected.Inactive"),
        ("ListBoxItem.SelectedInactive.Border",              "ABrush.Tone5.Border.Selected.Inactive"),
        ("ListBoxItem.SelectedActive.Background",            "ABrush.Tone5.Background.Selected"),
        ("ListBoxItem.SelectedActive.Border",                "ABrush.Tone5.Border.Selected"),
        ("CheckBox.Static.Background",                       "ABrush.Tone5.Background.Static"),
        ("CheckBox.Static.Border",                           "ABrush.Tone5.Border.Static"),
        ("CheckBox.MouseOver.Background",                    "ABrush.Tone5.Background.MouseOver"),
        ("CheckBox.MouseOver.Border",                        "ABrush.Tone5.Border.MouseOver"),
        ("CheckBox.Disabled.Background",                     "ABrush.Tone5.Background.Disabled"),
        ("CheckBox.Disabled.Border",                         "ABrush.Tone5.Border.Disabled"),
        ("CheckBox.Pressed.Background",                      "ABrush.Tone5.Background.MouseDown"),
        ("CheckBox.Pressed.Border",                          "ABrush.Tone5.Border.MouseDown"),
        ("CheckBox.Static.Glyph",                            "ABrush.Glyph.Static"),
        ("CheckBox.Pressed.Glyph",                           "ABrush.Glyph.MouseDown"),
        ("CheckBox.MouseOver.Glyph",                         "ABrush.Glyph.MouseOver"),
        ("CheckBox.Disabled.Glyph",                          "ABrush.Glyph.Disabled"),
        ("RadioButton.Static.Background",                    "ABrush.Tone5.Background.Static"),
        ("RadioButton.Static.Border",                        "ABrush.Tone5.Border.Static"),
        ("RadioButton.MouseOver.Background",                 "ABrush.Tone5.Background.MouseOver"),
        ("RadioButton.MouseOver.Border",                     "ABrush.Tone5.Border.MouseOver"),
        ("RadioButton.Pressed.Background",                   "ABrush.Tone5.Background.MouseDown"),
        ("RadioButton.Pressed.Border",                       "ABrush.Tone5.Border.MouseDown"),
        ("RadioButton.Disabled.Background",                  "ABrush.Tone5.Background.Disabled"),
        ("RadioButton.Disabled.Border",                      "ABrush.Tone5.Border.Disabled"),
        ("RadioButton.Static.Glyph",                         "ABrush.Glyph.Static"),
        ("RadioButton.MouseOver.Glyph",                      "ABrush.Glyph.MouseOver"),
        ("RadioButton.Pressed.Glyph",                        "ABrush.Glyph.MouseDown"),
        ("RadioButton.Disabled.Glyph",                       "ABrush.Glyph.Disabled"),
        ("ScrollBar.Static.Background",                      "ABrush.Tone5.Background.Static"),
        ("ScrollBar.Static.Border",                          "ABrush.Tone5.Border.Static"),
        ("ScrollBarButton.Static.Background",                "ABrush.Tone6.Background.Static"),
        ("ScrollBarButton.Static.Border",                    "ABrush.Tone5.Border.Static"),
        ("ScrollBar.Pressed.Glyph",                          "ABrush.Glyph.MouseDown"),
        ("ScrollBar.MouseOver.Glyph",                        "ABrush.Glyph.MouseOver"),
        ("ScrollBar.Disabled.Glyph",                         "ABrush.Glyph.Disabled"),
        ("ScrollBar.Static.Glyph",                           "ABrush.Glyph.Static"),
        ("ScrollBarSink.MouseOver.Background",               "ABrush.Tone1.Background.Static"),
        ("ScrollBar.MouseOver.Background",                   "ABrush.Tone5.Background.MouseOver"),
        ("ScrollBar.MouseOver.Border",                       "ABrush.Tone5.Border.MouseOver"),
        ("ScrollBar.Pressed.Background",                     "ABrush.Tone5.Background.MouseDown"),
        ("ScrollBar.Pressed.Border",                         "ABrush.Tone5.Border.MouseDown"),
        ("ScrollBar.Disabled.Background",                    "ABrush.Tone5.Background.Disabled"),
        ("ScrollBar.Disabled.Border",                        "ABrush.Tone5.Border.Disabled"),
        ("ScrollBar.MouseOver.Thumb",                        "ABrush.Tone7.Background.MouseOver"),
        ("ScrollBar.Pressed.Thumb",                          "ABrush.Tone7.Background.MouseDown"),
        ("ScrollBar.Static.Thumb",                           "ABrush.Tone7.Background.Static"),
        ("TabItem.Selected.Background",                      "ABrush.Tone6.Background.Static"),
        ("TabItem.Selected.Border",                          "ABrush.Tone5.Border.Selected"),
        ("TabItem.Static.Background",                        "ABrush.Tone5.Background.Static"),
        ("TabItem.Static.Border",                            "ABrush.Tone5.Border.Static"),
        ("TabItem.MouseOver.Background",                     "ABrush.Tone5.Background.MouseOver"),
        ("TabItem.MouseOver.Border",                         "ABrush.Tone5.Border.MouseOver"),
        ("TabItem.Disabled.Background",                      "ABrush.Tone5.Background.Disabled"),
        ("TabItem.Disabled.Border",                          "ABrush.Tone5.Border.Disabled"),
        ("Expander.MouseOver.Circle.Fill",                   "ABrush.Tone5.Background.MouseOver"),
        ("Expander.MouseOver.Circle.Stroke",                 "ABrush.Tone5.Border.MouseOver"),
        ("Expander.Pressed.Circle.Fill",                     "ABrush.Tone5.Background.MouseDown"),
        ("Expander.Pressed.Circle.Stroke",                   "ABrush.Tone5.Border.MouseDown"),
        ("Expander.Disabled.Circle.Fill",                    "ABrush.Tone5.Background.Disabled"),
        ("Expander.Disabled.Circle.Stroke",                  "ABrush.Tone5.Border.Disabled"),
        ("Expander.Static.Circle.Fill",                      "ABrush.Tone5.Background.Static"),
        ("Expander.Static.Circle.Stroke",                    "ABrush.Tone5.Border.Static"),
        ("Expander.Static.Arrow.Stroke",                     "ABrush.Glyph.Static"),
        ("Expander.MouseOver.Arrow.Stroke",                  "ABrush.Glyph.MouseOver"),
        ("Expander.Pressed.Arrow.Stroke",                    "ABrush.Glyph.MouseDown"),
        ("Expander.Disabled.Arrow.Stroke",                   "ABrush.Glyph.Disabled"),
        ("GridSplitter.Static.Background",                   "ABrush.Tone5.Background.Static"),
        ("GroupBox.Static.Background",                       null),
        ("GroupBox.Static.Border",                           "ABrush.Tone6.Border.Static"),
        ("GroupBox.Header.Static.Background",                "ABrush.Tone5.Background.Static"),
        ("GroupBox.Header.Static.Border",                    "ABrush.Tone6.Border.Static"),
        ("GroupBox.Header.Foreground",                       "ABrush.Foreground.Static"),
        ("GroupBox.Header.Background.Disabled",              "ABrush.Tone5.Background.Disabled"),
        ("GroupBox.Header.Static.Border.Disabled",           "ABrush.Tone6.Border.Disabled"),
        ("GroupBox.Header.Foreground.Disabled",              "ABrush.Foreground.Disabled"),
        ("Menu.Static.Background",                           null),
        ("MenuItem.Static.Background",                       "ABrush.Tone5.Background.Static"),
        ("MenuItem.IconBar.Static.Background",               "ABrush.Tone6.Background.Static"),
        ("MenuItem.IconBar.Static.Border",                   "ABrush.Tone6.Border.Static"),
        ("MenuItem.Square.Static.Background",                "ABrush.Tone6.Background.Static"),
        ("MenuItem.Square.Static.Border",                    "ABrush.Tone8.Border.Static"),
        ("MenuItem.MouseOver.Background",                    "ABrush.AccentTone2.Background.Static"),
        ("MenuItem.MouseOver.Border",                        "ABrush.Tone5.Border.MouseOver"),
        ("MenuItem.Disabled.Background",                     "ABrush.Tone5.Background.MouseOver"),
        ("Popup.Static.Background",                          "ABrush.Tone5.Background.Static"),
        ("Popup.Static.Border",                              "ABrush.Tone7.Border.Static"),
        ("Popup.Static.Foreground",                          "ABrush.Foreground.Static"),
        ("Popup.Disabled.Background",                        "ABrush.Tone4.Background.Disabled"),
        ("Popup.Disabled.Border",                            "ABrush.Tone4.Border.Disabled"),
        ("Popup.Disabled.Foreground",                        "ABrush.Foreground.Disabled"),
        ("MenuItem.Static.Glyph",                            "ABrush.Glyph.Static"),
        ("MenuItem.Disabled.Glyph",                          "ABrush.Glyph.Disabled"),
        ("SliderThumb.MouseOver.Background",                 "ABrush.Tone5.Background.MouseOver"),
        ("SliderThumb.MouseOver.Border",                     "ABrush.Tone5.Border.MouseOver"),
        ("SliderThumb.Pressed.Background",                   "ABrush.Tone5.Background.MouseDown"),
        ("SliderThumb.Pressed.Border",                       "ABrush.Tone5.Border.MouseDown"),
        ("SliderThumb.Disabled.Background",                  "ABrush.Tone5.Background.Disabled"),
        ("SliderThumb.Disabled.Border",                      "ABrush.Tone5.Border.Disabled"),
        ("SliderThumb.Static.Background",                    "ABrush.Tone5.Background.Static"),
        ("SliderThumb.Static.Border",                        "ABrush.Tone5.Border.Static"),
        ("SliderThumb.Track.Background",                     "ABrush.Tone5.Background.Static"),
        ("SliderThumb.Track.Border",                         "ABrush.Tone5.Border.Static"),
        ("SliderThumb.Static.Foreground",                    "ABrush.Glyph.Disabled"),
        ("SliderThumb.Track.Progress.Background",            "ABrush.ColourfulGlyph.Static"),
        ("SliderThumb.Track.Progress.Border",                "ABrush.Tone5.Border.Static"),
        ("ProgressBar.Progress",                             "ABrush.ColourfulGlyph.Static"),
        ("ProgressBar.Background",                           "ABrush.Tone5.Background.Static"),
        ("ProgressBar.Border",                               "ABrush.Tone5.Border.Static"),
        ("TreeView.Static.Background",                       "ABrush.Tone4.Background.Static"),
        ("TreeView.Static.Border",                           "ABrush.Tone4.Border.Static"),
        ("TreeView.Disabled.Background",                     "ABrush.Tone4.Background.Disabled"),
        ("TreeView.Disabled.Border",                         "ABrush.Tone4.Border.Disabled"),
        ("TreeViewItem.Static.Background",                   null),
        ("TreeViewItem.Static.Border",                       "ABrush.Tone5.Border.Static"),
        ("TreeViewItem.Selected.Background",                 "ABrush.Tone7.Background.Selected"),
        ("TreeViewItem.Selected.Border",                     "ABrush.Tone7.Border.Selected"),
        ("TreeViewItem.Selected.Inactive.Background",        "ABrush.Tone6.Background.Selected.Inactive"),
        ("TreeViewItem.Selected.Inactive.Border",            "ABrush.Tone6.Border.Selected.Inactive"),
        ("TreeViewItem.MouseOver.Background",                "ABrush.Tone6.Background.MouseOver"),
        ("TreeViewItem.MouseOver.Border",                    "ABrush.Tone6.Border.MouseOver"),
        ("TreeViewItem.MouseDown.Background",                "ABrush.Tone6.Background.MouseDown"),
        ("TreeViewItem.MouseDown.Border",                    "ABrush.Tone6.Border.MouseDown"),
        ("DataGrid.Static.Background",                       "ABrush.Tone4.Background.Static"),
        ("DataGrid.Static.Border",                           "ABrush.Tone4.Border.Static"),
        ("DataGrid.HorizontalSeparatorBrush",                "ABrush.Tone7.Background.Static"),
        ("DataGrid.VerticalSeparatorBrush",                  "ABrush.Tone7.Background.Static"),
        ("DataGrid.HeaderItem.Static.Background",            "ABrush.Tone6.Background.Static"),
        ("DataGrid.HeaderItem.MouseOver.Background",         "ABrush.Tone6.Background.MouseOver"),
        ("DataGrid.HeaderItem.MouseDown.Background",         "ABrush.Tone6.Background.MouseDown"),
        ("DataGrid.RowHeader.Static.Background",             "ABrush.Tone6.Background.Static"),
        ("DataGrid.Row.Selected.Background",                 "ABrush.Tone5.Background.Selected"),
        ("DataGrid.CellItem.Static.Background",              "ABrush.Tone5.Background.Static"),
        ("DataGrid.CellItem.MouseOver.Background",           "ABrush.Tone5.Background.MouseOver"),
        ("Window.Static.Background",                         "ABrush.Tone3.Background.Static"),
        ("Window.Static.Border",                             "ABrush.Tone5.Border.Static"),
        ("Window.Static.Foreground",                         "ABrush.Foreground.Static"),
        ("Window.Static.Title.Background",                   "ABrush.Tone6.Background.Static"),
    ];
}