// 
// Copyright (c) 2023-2025 REghZy
// 
// This file is part of PFXToolKitUI.
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with PFXToolKitUI. If not, see <https://www.gnu.org/licenses/>.
// 

namespace PFXToolKitUI.Avalonia.Themes;

public static class ControlColourMappings {
    public static (string, string)[] PathToThemeKey => [ 
        // "Full Mapping Path",                                          "ThemeKey"
        ("General/PanelBorderBrush",                                     "PanelBorderBrush"),
        ("General/PanelBackground0",                                     "PanelBackground0"),
        ("General/PanelBackground1",                                     "PanelBackground1"),
        ("General/PanelBackground2",                                     "PanelBackground2"),
        ("General/PanelBackground3",                                     "PanelBackground3"),
        ("General/PanelBackground4",                                     "PanelBackground4"),
        ("General/Button/Background",                                    "Button.Static.Background"),
        ("General/Button/Border",                                        "Button.Static.Border"),
        ("General/Button/Background (MouseOver)",                        "Button.MouseOver.Background"),
        ("General/Button/Border (MouseOver)",                            "Button.MouseOver.Border"),
        ("General/Button/Background (Pressed)",                          "Button.Pressed.Background"),
        ("General/Button/Border (Pressed)",                              "Button.Pressed.Border"),
        ("General/Button/Background (Disabled)",                         "Button.Disabled.Background"),
        ("General/Button/Border (Disabled)",                             "Button.Disabled.Border"),
        ("General/Button/Foreground",                                    "Button.Static.Foreground"),
        ("General/Button/Disabled/Foreground",                           "Button.Disabled.Foreground"),
        ("General/Button/Background (Defaulted)",                        "Button.Defaulted.Background"),
        ("General/Button/Border (Defaulted)",                            "Button.Defaulted.Border"),
        ("General/ButtonSpinner/Border (Error)",                         "ButtonSpinner.Error.Border"),
        ("General/ToggleButton/Background (Checked)",                    "ToggleButton.IsChecked.Background"),
        ("General/ToggleButton/Border (Checked)",                        "ToggleButton.IsChecked.Border"),
        ("General/ToggleButton/Background (Checked, Pressed)",           "ToggleButton.Pressed.IsChecked.Background"),
        ("General/ToggleButton/Border (Checked, Pressed)",               "ToggleButton.Pressed.IsChecked.Border"),
        ("General/ToggleButton/Background (Checked, MouseOver)",         "ToggleButton.MouseOver.IsChecked.Background"),
        ("General/ToggleButton/Border (Checked, MouseOver)",             "ToggleButton.MouseOver.IsChecked.Border"),
        ("General/ComboBox/Background",                                  "ComboBox.Static.Background"),
        ("General/ComboBox/Border",                                      "ComboBox.Static.Border"),
        ("General/ComboBox/Foreground",                                  "ComboBox.Static.Foreground"),
        ("General/ComboBox (Editable)/Background",                       "ComboBox.Static.Editable.Background"),
        ("General/ComboBox (Editable)/Border",                           "ComboBox.Static.Editable.Border"),
        ("General/ComboBoxButton (Editable)/Background",                 "ComboBox.Static.Editable.Button.Background"),
        ("General/ComboBoxButton (Editable)/Border",                     "ComboBox.Static.Editable.Button.Border"),
        ("General/ComboBoxButton/Background",                            "ComboBox.Button.Static.Background"),
        ("General/ComboBoxButton/Border",                                "ComboBox.Button.Static.Border"),
        ("General/ComboBox/Glyph (MouseOver)",                           "ComboBox.MouseOver.Glyph"),
        ("General/ComboBox/Background (MouseOver)",                      "ComboBox.MouseOver.Background"),
        ("General/ComboBox/Border (MouseOver)",                          "ComboBox.MouseOver.Border"),
        ("General/ComboBox (Editable)/Background (MouseOver)",           "ComboBox.MouseOver.Editable.Background"),
        ("General/ComboBox (Editable)/Border (MouseOver)",               "ComboBox.MouseOver.Editable.Border"),
        ("General/ComboBoxButton (Editable)/Background (MouseOver)",     "ComboBox.MouseOver.Editable.Button.Background"),
        ("General/ComboBoxButton (Editable)/Border (MouseOver)",         "ComboBox.MouseOver.Editable.Button.Border"),
        ("General/ComboBox/Glyph (Pressed)",                             "ComboBox.Pressed.Glyph"),
        ("General/ComboBox/Background (Pressed)",                        "ComboBox.Pressed.Background"),
        ("General/ComboBox/Border (Pressed)",                            "ComboBox.Pressed.Border"),
        ("General/ComboBox (Editable)/Background (Pressed)",             "ComboBox.Pressed.Editable.Background"),
        ("General/ComboBox (Editable)/Border (Pressed)",                 "ComboBox.Pressed.Editable.Border"),
        ("General/ComboBoxButton (Editable)/Background (Pressed)",       "ComboBox.Pressed.Editable.Button.Background"),
        ("General/ComboBoxButton (Editable)/Border (Pressed)",           "ComboBox.Pressed.Editable.Button.Border"),
        ("General/ComboBox/Glyph (Disabled)",                            "ComboBox.Disabled.Glyph"),
        ("General/ComboBox/Background (Disabled)",                       "ComboBox.Disabled.Background"),
        ("General/ComboBox/Border (Disabled)",                           "ComboBox.Disabled.Border"),
        ("General/ComboBox (Editable)/Background (Disabled)",            "ComboBox.Disabled.Editable.Background"),
        ("General/ComboBox (Editable)/Border (Disabled)",                "ComboBox.Disabled.Editable.Border"),
        ("General/ComboBoxButton (Editable)/Background (Disabled)",      "ComboBox.Disabled.Editable.Button.Background"),
        ("General/ComboBoxButton (Editable)/Border (Disabled)",          "ComboBox.Disabled.Editable.Button.Border"),
        ("General/ComboBox/Glyph",                                       "ComboBox.Static.Glyph"),
        ("General/ComboBoxItem/ItemView/Background (Hover)",             "ComboBoxItem.ItemView.Hover.Background"),
        ("General/ComboBoxItem/ItemView/Border (Hover)",                 "ComboBoxItem.ItemView.Hover.Border"),
        ("General/ComboBoxItem/ItemView/Background (Selected)",          "ComboBoxItem.ItemView.Selected.Background"),
        ("General/ComboBoxItem/ItemView/Border (Selected)",              "ComboBoxItem.ItemView.Selected.Border"),
        ("General/ComboBoxItem/ItemView/Background (Selected, Hover)",   "ComboBoxItem.ItemView.SelectedHover.Background"),
        ("General/ComboBoxItem/ItemView/Border (Selected, Hover)",       "ComboBoxItem.ItemView.SelectedHover.Border"),
        ("General/ComboBoxItem/ItemView/Background (Selected, NoFocus)", "ComboBoxItem.ItemView.SelectedNoFocus.Background"),
        ("General/ComboBoxItem/ItemView/Border (Selected, NoFocus)",     "ComboBoxItem.ItemView.SelectedNoFocus.Border"),
        ("General/ComboBoxItem/ItemView/Border (Focused)",               "ComboBoxItem.ItemView.Focus.Border"),
        ("General/ComboBoxItem/ItemView/Background (Hover, Focused)",    "ComboBoxItem.ItemView.HoverFocus.Background"),
        ("General/ComboBoxItem/ItemView/Border (Hover, Focused)",        "ComboBoxItem.ItemView.HoverFocus.Border"),
        ("General/TextBox/Background",                                   "TextBox.Static.Background"),
        ("General/TextBox/Border",                                       "TextBox.Static.Border"),
        ("General/TextBox/Border (MouseOver)",                           "TextBox.MouseOver.Border"),
        ("General/TextBox/Border (Focused)",                             "TextBox.Focus.Border"),
        ("General/TextBox/Selection (Inactive)",                         "TextBox.Selection.Inactive"),
        ("General/TextBox/Selection",                                    "TextBox.Selection"),
        ("General/TextBox/Border (Error)",                               "TextBox.Error.Border"),
        ("General/ListBox/Background",                                   "ListBox.Static.Background"),
        ("General/ListBox/Border",                                       "ListBox.Static.Border"),
        ("General/ListBox/Background (Disabled)",                        "ListBox.Disabled.Background"),
        ("General/ListBox/Border (Disabled)",                            "ListBox.Disabled.Border"),
        ("General/ListBoxItem/Background (MouseOver)",                   "ListBoxItem.MouseOver.Background"),
        ("General/ListBoxItem/Border (MouseOver)",                       "ListBoxItem.MouseOver.Border"),
        ("General/ListBoxItem/Background (Selected, Inactive)",          "ListBoxItem.SelectedInactive.Background"),
        ("General/ListBoxItem/Border (Selected, Inactive)",              "ListBoxItem.SelectedInactive.Border"),
        ("General/ListBoxItem/Background (Selected)",                    "ListBoxItem.SelectedActive.Background"),
        ("General/ListBoxItem/Border (Selected)",                        "ListBoxItem.SelectedActive.Border"),
        ("General/CheckBox/Background",                                  "CheckBox.Static.Background"),
        ("General/CheckBox/Border",                                      "CheckBox.Static.Border"),
        ("General/CheckBox/Background (MouseOver)",                      "CheckBox.MouseOver.Background"),
        ("General/CheckBox/Border (MouseOver)",                          "CheckBox.MouseOver.Border"),
        ("General/CheckBox/Background (Disabled)",                       "CheckBox.Disabled.Background"),
        ("General/CheckBox/Border (Disabled)",                           "CheckBox.Disabled.Border"),
        ("General/CheckBox/Background (Pressed)",                        "CheckBox.Pressed.Background"),
        ("General/CheckBox/Border (Pressed)",                            "CheckBox.Pressed.Border"),
        ("General/CheckBox/Glyph",                                       "CheckBox.Static.Glyph"),
        ("General/CheckBox/Glyph (Pressed)",                             "CheckBox.Pressed.Glyph"),
        ("General/CheckBox/Glyph (MouseOver)",                           "CheckBox.MouseOver.Glyph"),
        ("General/CheckBox/Glyph (Disabled)",                            "CheckBox.Disabled.Glyph"),
        ("General/RadioButton/Background",                               "RadioButton.Static.Background"),
        ("General/RadioButton/Border",                                   "RadioButton.Static.Border"),
        ("General/RadioButton/Background (MouseOver)",                   "RadioButton.MouseOver.Background"),
        ("General/RadioButton/Border (MouseOver)",                       "RadioButton.MouseOver.Border"),
        ("General/RadioButton/Background (Pressed)",                     "RadioButton.Pressed.Background"),
        ("General/RadioButton/Border (Pressed)",                         "RadioButton.Pressed.Border"),
        ("General/RadioButton/Background (Disabled)",                    "RadioButton.Disabled.Background"),
        ("General/RadioButton/Border (Disabled)",                        "RadioButton.Disabled.Border"),
        ("General/RadioButton/Glyph",                                    "RadioButton.Static.Glyph"),
        ("General/RadioButton/Glyph (MouseOver)",                        "RadioButton.MouseOver.Glyph"),
        ("General/RadioButton/Glyph (Pressed)",                          "RadioButton.Pressed.Glyph"),
        ("General/RadioButton/Glyph (Disabled)",                         "RadioButton.Disabled.Glyph"),
        ("General/ScrollBar/Background",                                 "ScrollBar.Static.Background"),
        ("General/ScrollBar/Border",                                     "ScrollBar.Static.Border"),
        ("General/ScrollBarButton/Background",                           "ScrollBarButton.Static.Background"),
        ("General/ScrollBarButton/Border",                               "ScrollBarButton.Static.Border"),
        ("General/ScrollBar/Glyph (Pressed)",                            "ScrollBar.Pressed.Glyph"),
        ("General/ScrollBar/Glyph (MouseOver)",                          "ScrollBar.MouseOver.Glyph"),
        ("General/ScrollBar/Glyph (Disabled)",                           "ScrollBar.Disabled.Glyph"),
        ("General/ScrollBar/Glyph",                                      "ScrollBar.Static.Glyph"),
        ("General/ScrollBarSink/Background (MouseOver)",                 "ScrollBarSink.MouseOver.Background"),
        ("General/ScrollBar/Background (MouseOver)",                     "ScrollBar.MouseOver.Background"),
        ("General/ScrollBar/Border (MouseOver)",                         "ScrollBar.MouseOver.Border"),
        ("General/ScrollBar/Background (Pressed)",                       "ScrollBar.Pressed.Background"),
        ("General/ScrollBar/Border (Pressed)",                           "ScrollBar.Pressed.Border"),
        ("General/ScrollBar/Background (Disabled)",                      "ScrollBar.Disabled.Background"),
        ("General/ScrollBar/Border (Disabled)",                          "ScrollBar.Disabled.Border"),
        ("General/ScrollBar/Thumb (MouseOver)",                          "ScrollBar.MouseOver.Thumb"),
        ("General/ScrollBar/Thumb (Pressed)",                            "ScrollBar.Pressed.Thumb"),
        ("General/ScrollBar/Thumb",                                      "ScrollBar.Static.Thumb"),
        ("General/TabItem/Background (Selected)",                        "TabItem.Selected.Background"),
        ("General/TabItem/Border (Selected)",                            "TabItem.Selected.Border"),
        ("General/TabItem/Background",                                   "TabItem.Static.Background"),
        ("General/TabItem/Border",                                       "TabItem.Static.Border"),
        ("General/TabItem/Background (MouseOver)",                       "TabItem.MouseOver.Background"),
        ("General/TabItem/Border (MouseOver)",                           "TabItem.MouseOver.Border"),
        ("General/TabItem/Background (Disabled)",                        "TabItem.Disabled.Background"),
        ("General/TabItem/Border (Disabled)",                            "TabItem.Disabled.Border"),
        ("General/Expander/Circle/Fill (MouseOver)",                     "Expander.MouseOver.Circle.Fill"),
        ("General/Expander/Circle/Stroke (MouseOver)",                   "Expander.MouseOver.Circle.Stroke"),
        ("General/Expander/Circle/Fill (Pressed)",                       "Expander.Pressed.Circle.Fill"),
        ("General/Expander/Circle/Stroke (Pressed)",                     "Expander.Pressed.Circle.Stroke"),
        ("General/Expander/Circle/Fill (Disabled)",                      "Expander.Disabled.Circle.Fill"),
        ("General/Expander/Circle/Stroke (Disabled)",                    "Expander.Disabled.Circle.Stroke"),
        ("General/Expander/Circle/Fill",                                 "Expander.Static.Circle.Fill"),
        ("General/Expander/Circle/Stroke",                               "Expander.Static.Circle.Stroke"),
        ("General/Expander/Arrow/Stroke",                                "Expander.Static.Arrow.Stroke"),
        ("General/Expander/Arrow/Stroke (MouseOver)",                    "Expander.MouseOver.Arrow.Stroke"),
        ("General/Expander/Arrow/Stroke (Pressed)",                      "Expander.Pressed.Arrow.Stroke"),
        ("General/Expander/Arrow/Stroke (Disabled)",                     "Expander.Disabled.Arrow.Stroke"),
        ("General/GridSplitter/Background",                              "GridSplitter.Static.Background"),
        ("General/GroupBox/Background",                                  "GroupBox.Static.Background"),
        ("General/GroupBox/Border",                                      "GroupBox.Static.Border"),
        ("General/GroupBox/Header/Background",                           "GroupBox.Header.Static.Background"),
        ("General/GroupBox/Header/Border",                               "GroupBox.Header.Static.Border"),
        ("General/GroupBox/Header/Foreground",                           "GroupBox.Header.Foreground"),
        ("General/GroupBox/Header/Background (Disabled)",                "GroupBox.Header.Background.Disabled"),
        ("General/GroupBox/Header/Border (Disabled)",                    "GroupBox.Header.Static.Border.Disabled"),
        ("General/GroupBox/Header/Foreground (Disabled)",                "GroupBox.Header.Foreground.Disabled"),
        ("General/Menu/Background",                                      "Menu.Static.Background"),
        ("General/MenuItem/Background",                                  "MenuItem.Static.Background"),
        ("General/MenuItem/IconBar/Background",                          "MenuItem.IconBar.Static.Background"),
        ("General/MenuItem/IconBar/Border",                              "MenuItem.IconBar.Static.Border"),
        ("General/MenuItem/Square/Background",                           "MenuItem.Square.Static.Background"),
        ("General/MenuItem/Square/Border",                               "MenuItem.Square.Static.Border"),
        ("General/MenuItem/Background (MouseOver)",                      "MenuItem.MouseOver.Background"),
        ("General/MenuItem/Border (MouseOver)",                          "MenuItem.MouseOver.Border"),
        ("General/MenuItem/Background (Disabled)",                       "MenuItem.Disabled.Background"),
        ("General/Popup/Background",                                     "Popup.Static.Background"),
        ("General/Popup/Border",                                         "Popup.Static.Border"),
        ("General/Popup/Foreground",                                     "Popup.Static.Foreground"),
        ("General/Popup/Background (Disabled)",                          "Popup.Disabled.Background"),
        ("General/Popup/Border (Disabled)",                              "Popup.Disabled.Border"),
        ("General/Popup/Foreground (Disabled)",                          "Popup.Disabled.Foreground"),
        ("General/MenuItem/Glyph",                                       "MenuItem.Static.Glyph"),
        ("General/MenuItem/Glyph (Disabled)",                            "MenuItem.Disabled.Glyph"),
        ("General/SliderThumb/Background (MouseOver)",                   "SliderThumb.MouseOver.Background"),
        ("General/SliderThumb/Border (MouseOver)",                       "SliderThumb.MouseOver.Border"),
        ("General/SliderThumb/Background (Pressed)",                     "SliderThumb.Pressed.Background"),
        ("General/SliderThumb/Border (Pressed)",                         "SliderThumb.Pressed.Border"),
        ("General/SliderThumb/Background (Disabled)",                    "SliderThumb.Disabled.Background"),
        ("General/SliderThumb/Border (Disabled)",                        "SliderThumb.Disabled.Border"),
        ("General/SliderThumb/Background",                               "SliderThumb.Static.Background"),
        ("General/SliderThumb/Border",                                   "SliderThumb.Static.Border"),
        ("General/SliderThumb/Track/Background",                         "SliderThumb.Track.Background"),
        ("General/SliderThumb/Track/Border",                             "SliderThumb.Track.Border"),
        ("General/SliderThumb/Foreground",                               "SliderThumb.Static.Foreground"),
        ("General/SliderThumb/Track/Progress/Background",                "SliderThumb.Track.Progress.Background"),
        ("General/SliderThumb/Track/Progress/Border",                    "SliderThumb.Track.Progress.Border"),
        ("General/ProgressBar/Progress",                                 "ProgressBar.Progress"),
        ("General/ProgressBar/Background",                               "ProgressBar.Background"),
        ("General/ProgressBar/Border",                                   "ProgressBar.Border"),
        ("General/TreeView/Background",                                  "TreeView.Static.Background"),
        ("General/TreeView/Border",                                      "TreeView.Static.Border"),
        ("General/TreeView/Background (Disabled)",                       "TreeView.Disabled.Background"),
        ("General/TreeView/Border (Disabled)",                           "TreeView.Disabled.Border"),
        ("General/TreeViewItem/Background",                              "TreeViewItem.Static.Background"),
        ("General/TreeViewItem/Border",                                  "TreeViewItem.Static.Border"),
        ("General/TreeViewItem/Background (Selected)",                   "TreeViewItem.Selected.Background"),
        ("General/TreeViewItem/Border (Selected)",                       "TreeViewItem.Selected.Border"),
        ("General/TreeViewItem/Background (Selected, Inactive)",         "TreeViewItem.Selected.Inactive.Background"),
        ("General/TreeViewItem/Border (Selected, Inactive)",             "TreeViewItem.Selected.Inactive.Border"),
        ("General/TreeViewItem/Background (MouseOver)",                  "TreeViewItem.MouseOver.Background"),
        ("General/TreeViewItem/Border (MouseOver)",                      "TreeViewItem.MouseOver.Border"),
        ("General/TreeViewItem/Background (MouseDown)",                  "TreeViewItem.MouseDown.Background"),
        ("General/TreeViewItem/Border (MouseDown)",                      "TreeViewItem.MouseDown.Border"),
        ("General/DataGrid/Background",                                  "DataGrid.Static.Background"),
        ("General/DataGrid/Border",                                      "DataGrid.Static.Border"),
        ("General/DataGrid/HorizontalSeparatorBrush",                    "DataGrid.HorizontalSeparatorBrush"),
        ("General/DataGrid/VerticalSeparatorBrush",                      "DataGrid.VerticalSeparatorBrush"),
        ("General/DataGrid/HeaderItem/Background",                       "DataGrid.HeaderItem.Static.Background"),
        ("General/DataGrid/HeaderItem/Background (MouseOver)",           "DataGrid.HeaderItem.MouseOver.Background"),
        ("General/DataGrid/HeaderItem/Background (MouseDown)",           "DataGrid.HeaderItem.MouseDown.Background"),
        ("General/DataGrid/RowHeader/Background",                        "DataGrid.RowHeader.Static.Background"),
        ("General/DataGrid/Row/Background (Selected)",                   "DataGrid.Row.Selected.Background"),
        ("General/DataGrid/CellItem/Background",                         "DataGrid.CellItem.Static.Background"),
        ("General/DataGrid/CellItem/Background (MouseOver)",             "DataGrid.CellItem.MouseOver.Background"),
        ("General/Window/Background",                                    "Window.Static.Background"),
        ("General/Window/Border",                                        "Window.Static.Border"),
        ("General/Window/Foreground",                                    "Window.Static.Foreground"),
        ("General/Window/Title/Background",                              "Window.Static.Title.Background"),
    ];
}